version: '3.3'

services:
  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - static:/static
    ports:
      - "8001:8001"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - frontend:/app/build
    ports:
      - "3000:3000"

  db:
    image: postgres:14.6-alpine
    env_file:
      - ./.env.dev.db

volumes:
  static:
  frontend:
