version: '3.3'

services:
  assignment_2:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./assignment_2:/assignment_2
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    env_file:
      - ./.env.dev.db