# Generated by Django 4.2.3 on 2023-11-20 14:06

import caregivers_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caregivers_app', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, upload_to=caregivers_app.models.unique_directory_path)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('caregiving_type', models.CharField(max_length=63)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('house_rules', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='caregivers_app.member')),
                ('house_number', models.CharField(max_length=7)),
                ('street', models.CharField(max_length=127)),
                ('town', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_caregiving_type', models.CharField(max_length=50)),
                ('other_requirements', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caregivers_app.member')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caregivers_app.caregiver'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caregivers_app.member'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caregivers_app.caregiver')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caregivers_app.job')),
            ],
            options={
                'unique_together': {('caregiver', 'job')},
            },
        ),
    ]
